/*
Suppression des relations 
*/
/*
*************************************************
ATTENTION NE PAS TOUCHER AUX LIGNES SUIVANTES
ELLES PERMETTENT SOUS ORACLE DE SUPPRIMER PROPREMENT LES RELATIONS.
LES RELATIONS DYNAMIQUES SONT SUPPRIMEES EN PREMIER.


AVEC D'AUTRES SGBD UN :
DROP TABLE [IF EXISTS] table_name;
DEVRAIT SUFFIRRE.
*************************************************
*/
prompt "Suppression des relations"
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE EMPRUNT CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE CARACTERISE CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE EXEMPLAIRE CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE ABONNE CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE MOT_CLEF CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE LIVRE CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE AUTEUR CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE ECRIT CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

/*
*************************************************
*/


/*
Création des relations 
*/

prompt "Création des relations"

CREATE TABLE LIVRE (
	ISBN VARCHAR(15), 
	TITRE VARCHAR(50) CONSTRAINT TITRLE_NOT_NULL NOT NULL,
	SIECLE NUMERIC(2,0),
	CATEGORIE VARCHAR(16),
	CONSTRAINT PK_ECRIT_LIVRE PRIMARY KEY (ISBN),
	CONSTRAINT SIECLE_COHERANT CHECK (SIECLE BETWEEN 0 and 21)
);

CREATE TABLE ABONNE (
	NUM_AB  NUMERIC(6,0),
	NOM VARCHAR(15) CONSTRAINT NOM_EXIST NOT NULL,
	PRENOM VARCHAR(20),
	VILLE VARCHAR(13), 
	AGE NUMERIC(3,0),
 	TARIF NUMERIC(3,0),
 	REDUC NUMERIC(3,0),
	CONSTRAINT DOM_AGE CHECK (AGE BETWEEN 0 AND 120),
	CONSTRAINT PK_ECRIT_ABONNE PRIMARY KEY (NUM_AB)
	);

CREATE TABLE EXEMPLAIRE (
	NUMERO NUMERIC(4,0), 
	DATE_ACHAT DATE, 
	PRIX NUMERIC(5,2), 
	CODE_PRET VARCHAR(20) ,
	ETAT VARCHAR(15), 
	ISBN  VARCHAR(15), 
	CONSTRAINT DOM_CODE_PRET CHECK (CODE_PRET IN ('EXCLU','EMPRUNTABLE','CONSULTABLE')),
	CONSTRAINT PK_ECRIT_EXEMPLAIRE PRIMARY KEY (NUMERO),
	CONSTRAINT ETATLOGIQUE CHECK (ETAT IN ('BON','ABIME','EN_REPARATION')),
	CONSTRAINT ISBN_FK FOREIGN KEY (ISBN) REFERENCES LIVRE(ISBN)
);

CREATE TABLE MOT_CLEF (
	MOT VARCHAR(16),
	CONSTRAINT PK_ECRIT_MOT_CLEF PRIMARY KEY (MOT)
);

CREATE TABLE EMPRUNT (
	NUM_AB  NUMERIC(6,0),
	NUM_EX NUMERIC (4,0) ,
	D_EMPRUNT DATE, 
	D_RETOUR DATE, 
	D_RET_REEL DATE, 
	NB_RELANCE NUMERIC(1,0),
	CONSTRAINT PK_ECRIT_EMPRUNT PRIMARY KEY (NUM_AB,NUM_EX,D_EMPRUNT),
	CONSTRAINT NB_RELANCE CHECK (NB_RELANCE IN (1,2,3))
);

CREATE TABLE CARACTERISE (
	ISBN VARCHAR(20), 
	MOT VARCHAR(20),
	CONSTRAINT PK_ECRIT_CARACTERISE PRIMARY KEY (ISBN,MOT)
);

